sudo: false
dist: trusty

cache:
  bundler: true

language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

before_install:
  - gem install bundler

install:
  - bundle install
  - bundle exec appraisal install

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - bundle exec appraisal rack rake spec:integration:rack
  - bundle exec appraisal rails-4.2 rake spec:integration:rails
  - bundle exec appraisal rails-5.0 rake spec:integration:rails
  - bundle exec appraisal rails-5.1 rake spec:integration:rails
  - bundle exec appraisal rails-5.2 rake spec:integration:rails
  - bundle exec appraisal sinatra rake spec:integration:sinatra
  - bundle exec rake spec:unit

after_success:
  - bundle exec codeclimate-test-reporter
