version: 2.1

commands:
  appraisal-install:
    description: Resolve and install dependencies for each appraisal
    steps:
      - run: bundle install && bundle exec appraisal install

  appraisal:
    description: Run a command in a single appraisal
    parameters:
      appraisal-name:
        description: Appraisal name
        type: string
      external-command:
        description: External command
        type: string
    steps:
      - run: bundle exec appraisal << parameters.appraisal-name >> << parameters.external-command >>

  appraisal-matrix:
    description: Matrix expansion
    parameters:
      rails-4-2:
        type: boolean
        default: true
      rails-5-0:
        type: boolean
        default: true
      rails-5-1:
        type: boolean
        default: true
      rails-5-2:
        type: boolean
        default: true
      rails-6-0:
        type: boolean
        default: true
      rails-head:
        type: boolean
        default: true
      sinatra:
        type: boolean
        default: true
      rack:
        type: boolean
        default: true
    steps:
      - when:
          condition: << parameters.rails-4-2 >>
          steps:
              - appraisal:
                  appraisal-name: 'rails-4-2'
                  external-command: 'rake spec:integration:rails'
      - when:
          condition: << parameters.rails-5-0 >>
          steps:
            - appraisal:
                appraisal-name: 'rails-5-0'
                external-command: 'rake spec:integration:rails'
      - when:
          condition: << parameters.rails-5-1 >>
          steps:
            - appraisal:
                appraisal-name: 'rails-5-1'
                external-command: 'rake spec:integration:rails'
      - when:
          condition: << parameters.rails-5-2 >>
          steps:
            - appraisal:
                appraisal-name: 'rails-5-2'
                external-command: 'rake spec:integration:rails'
      - when:
          condition: << parameters.rails-6-0 >>
          steps:
            - appraisal:
                appraisal-name: 'rails-6-0'
                external-command: 'rake spec:integration:rails'
      - when:
          condition: << parameters.rails-head >>
          steps:
            - appraisal:
                appraisal-name: 'rails-head'
                external-command: 'rake spec:integration:rails'
      - when:
          condition: << parameters.sinatra >>
          steps:
            - appraisal:
                appraisal-name: 'sinatra'
                external-command: 'rake spec:integration:sinatra'
      - when:
          condition: << parameters.rack >>
          steps:
            - appraisal:
                appraisal-name: 'rack'
                external-command: 'rake spec:integration:rack'

  cc-setup-coverage:
    description: Setup Code Climate
    parameters:
      url:
        description: Pre-built binary URL
        default: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        type: string
      version:
        default: latest
        type: string
    steps:
      - restore_cache:
          key: cc-setup-<< parameters.version >>
      - run:
          name: Setup coverage
          command: |
            if [[ $(command -v cc-test-reporter) == "" ]]; then
              mkdir -p tmp/
              sudo curl -s -o ./tmp/cc-test-reporter -L << parameters.url >>
              sudo chmod +x ./tmp/cc-test-reporter
            else
              echo "Already installed."
            fi
      - save_cache:
          key: cc-setup-<< parameters.version >>
          paths:
            - ./tmp/cc-test-reporter

executors:
  default:
    description: The official CircleCI Ruby Docker image
    parameters:
      tag:
        description: The circleci/ruby Docker image version tag
        type: string
        default: latest
    docker:
      - image: circleci/ruby:<< parameters.tag >>
    environment:
      - BUNDLE_JOBS: 4
      - BUNDLE_PATH: vendor/bundle
      - BUNDLE_RETRY: 3
    working_directory: ~/mailgun-tracking

jobs:
  checkout:
    executor: default
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - checkout
      - save_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  code-climate:
    executor:
      name: default
      tag: "2.6"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install the current environment to the system
          command: bundle install
      - cc-setup-coverage
      - run:
          name: Run specs
          command: |
            ./tmp/cc-test-reporter
            COVERAGE=true bundle exec rake
            ./tmp/cc-test-reporter after-build --exit-code $?

  rubocop:
    executor:
      name: default
      tag: "2.4"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - run: bundle install
      - run:
          name: Run RuboCop
          command: bundle exec rubocop --parallel

  ruby-2-4:
    executor:
      name: default
      tag: "2.4"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - appraisal-install
      - run: bundle exec rake spec:unit
      - appraisal-matrix:
          rails-6-0: false
          rails-head: false

  ruby-2-5:
    executor:
      name: default
      tag: "2.5"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - appraisal-install
      - run: bundle exec rake spec:unit
      - appraisal-matrix

  ruby-2-6:
    executor:
      name: default
      tag: "2.6"
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - appraisal-install
      - run: bundle exec rake spec:unit
      - appraisal-matrix

  ruby-head:
    executor: default
    steps:
      - restore_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
      - appraisal-install
      - run: bundle exec rake spec:unit
      - appraisal-matrix

workflows:
  version: 2
  default: &default
    jobs:
      - checkout
      - code-climate:
          requires:
            - checkout
      - rubocop:
          requires:
            - checkout
      - ruby-2-4:
          requires:
            - code-climate
            - rubocop
      - ruby-2-5:
          requires:
            - code-climate
            - rubocop
      - ruby-2-6:
          requires:
            - code-climate
            - rubocop
      - ruby-head:
          requires:
            - code-climate
            - rubocop

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    <<: *default
