name: Coverage

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4.x
      - name: Install a bundler gem
        run: |
          gem install bundler
      - name: Install the current environment to the system
        run:
          bundle install --jobs 4 --retry 3
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: COVERAGE=true bundle exec rake
